name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint-python:
    name: Lint (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flake8 and plugin
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-junit-xml

      - name: Run Flake8 → JUnit report
        run: |
          mkdir -p reports
          flake8 . --format=flake8_junit_xml --output-file=reports/flake8.xml || true

      - name: Upload Flake8 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: reports/flake8.xml

  test-python:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: lint-python

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          pytest --junitxml=reports/pytest.xml --cov=. --cov-report=xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/

  security-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    needs: test-python

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit → HTML report
        run: |
          mkdir -p reports
          bandit -r . -f html -o reports/bandit.html || true

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: reports/bandit.html
