name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ------ LINT ------
      - name: Install linters
        run: |
          pip install flake8 mypy

      - name: Run Flake8
        run: |
          flake8 .

      - name: Run mypy
        run: |
          mypy .


      # ------ TESTS ------
      - name: Run tests with coverage
        run: |
            pip install pytest pytest-cov
            mkdir -p coverage
            pytest app/Tests --verbose --cov=app --cov-report=term --cov-report=xml:coverage/coverage.xml

      - name: Upload coverage to Codecov
        if: success() && github.event_name != 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
