name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [node, python]
    steps:
      - uses: actions/checkout@v4

      - name: Set up ${{ matrix.language }}
        # Для Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      # Для Python
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: matrix.language == 'node'
        run: npm ci
      - name: Install dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-junit-xml

      - name: Run linter
        if: matrix.language == 'node'
        run: npm run lint:ci
      - name: Run Flake8 (generate JUnit report)
        if: matrix.language == 'python'
        run: |
          mkdir -p reports
          flake8 . --format=pytest --output-file=reports/flake8-report.xml

      - name: Upload lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report-${{ matrix.language }}
          path: |
            eslint-report.xml
            reports/flake8-report.xml
