name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint-node:
    name: Lint (Node.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (JUnit report)
        run: |
          # убедитесь, что eslint-junit-reporter установлен:
          # npm install --save-dev eslint-junit-reporter
          npm run lint:ci

      - name: Upload ESLint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.xml

  lint-python:
    name: Lint (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install flake8 + JUnit formatter
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-junit-xml

      - name: Run Flake8 (JUnit report)
        run: |
          mkdir -p reports
          # --format=pytest + flake8-junit-xml выводит JUnit в reports/flake8.xml
          flake8 . --format=pytest --output-file=reports/flake8.xml

      - name: Upload Flake8 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: reports/flake8.xml
